# Generated by Django 5.2.1 on 2025-05-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
